---

- name: "configuration play."
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
    ENVIRONMENT:        "{{ lookup('env', 'ENVIRONMENT') }}"
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES:   "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_HOST:       "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT:       "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME:   "{{ lookup('env', 'YPEORM_USERNAME') }}"
    TYPEORM_PASSWORD:   "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE:   "{{ lookup('env', 'TYPEORM_DATABASE') }}"

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      wait_for_connection:
        timeout: 600 # Maximum number of seconds to wait for

    - name: "install python for Ansible."
      # Your code here
      raw: test -e /usr/bin/python3 || sudo apt-get -y -q install python3
      changed_when: false
  roles:
    # Your code here
    - configure-server
