---
- name: Create backend directory
  file:
    path: ~/backend
    state: directory
    mode: '775'

- name: Copy backend dist artifact file
  copy:
    owner: ubuntu
    mode: '644'
    src: backend-artifact.tar.gz
    dest: "~/"

- name: Unarchive backend artifact "backend-artifact.tar.gz"
  unarchive:
    owner: ubuntu
    # mode: '644'
    src: ~/backend-artifact.tar.gz
    dest: ~/backend
    remote_src: yes

- name: start backend service
  become: yes
  become_user: ubuntu
  changed_when: false
  ignore_errors: yes
  command: pm2 stop backend || pm2 start --name backend npm -- start
  args:
    chdir: ~/backend

